### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Philipinho** [eirlis/web3j-example#6]
In no particular order, i'll work to implement the following features when i have time.

- [ ] Make use of Infura API

- [ ] Show wallet balance

- [ ] Coin transfer

- [ ] USD value of wallet balance

- [ ] Custom location of wallet file

- [ ] Ability to login to already created wallet
